#!/usr/bin/env python

# line style
NL = "\x0a"
# text style
BOLD = "\x02"
COLOURED = "\x03"
# text colour
WHITE = COLOURED + "0"
BLACK = COLOURED + "1"
DARK_BLUE = COLOURED + "2"
GREEN = COLOURED + "3"
RED = COLOURED + "4"
DARK_RED = COLOURED + "5"
PURPLE = COLOURED + "6"
GOLD = COLOURED + "7"
YELLOW = COLOURED + "8"
LIGHT_GREEN = COLOURED + "9"
LIGHT_BLUE = COLOURED + "10"
AQUA = COLOURED + "11"
BLUE = COLOURED + "12"
PINK = COLOURED + "14"
GREY = COLOURED + "15"